feat: web3FunctionVersion 2.0.0
gelatodigital/web3-functions-sdk pull request #25
Opened 2023-03-29 11:48 UTC by brandonchuah

2023-03-29 12:49 UTC, goums requested changes

2023-03-29 14:13 UTC, brandonchuah commented on package.json
> +    "crypto": "^1.0.1",
[95a29ae](https://github.com/gelatodigital/web3-functions-sdk/pull/25/commits/95a29aebc76c219882e1284f3df9a0bff43b1716)

2023-03-29 14:13 UTC, brandonchuah commented on yarn.lock
> +
[95a29ae](https://github.com/gelatodigital/web3-functions-sdk/pull/25/commits/95a29aebc76c219882e1284f3df9a0bff43b1716)

2023-04-25 12:21 UTC, goums requested changes

2023-04-25 12:21 UTC, goums commented on src/lib/types/Web3FunctionResult.ts
>    | { canExec: false; message: string };
I think I would prefer more separated types:
```
export type Web3FunctionResultV1 =
  | { canExec: true; callData: string; }
  | { canExec: false; message: string };

export type Web3FunctionResultV2 =
  | { canExec: true; callData: Web3FunctionResultCallData[]; }
  | { canExec: false; message: string };

export type Web3FunctionResult = Web3FunctionResultV1 | Web3FunctionResultV2
```

2023-05-03 11:28 UTC, merged