Hardhat readme
gelatodigital/web3-functions-sdk pull request #29
Opened 2023-05-16 21:02 UTC by donoso-eth

Readme updated with hardhat plugin infos

2023-05-17 12:20 UTC, goums requested changes

2023-05-17 16:22 UTC, goums commented on README.md
> +Config `hardhat.config.ts` Web3 Functions Plugin
```suggestion
Import Web3 functions Hardhat plugin into `hardhat.config.ts`:  
```

2023-05-17 16:22 UTC, goums commented on README.md
> +Use following command your your tests:
```suggestion
Use the following command to run your test:
```

2023-05-17 16:22 UTC, goums commented on README.md
> +  const { w3f } = hre;
Let's reindent properly the example

```suggestion
const { w3f } = hre;
```

2023-05-20 15:36 UTC, donoso-eth commented
Changes done as requested

2023-05-22 07:04 UTC, goums approved these changes

2023-05-22 07:05 UTC, merged